spring:
  mvc:
    log-request-details: false

kafka:
  aiven:
    properties:
      security:
        protocol: SSL
      ssl:
        truststore-location: file:${KAFKA_TRUSTSTORE_PATH}
        truststore-password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore-type: JKS
        keystore-location: file:${KAFKA_KEYSTORE_PATH}
        keystore-password: ${KAFKA_CREDSTORE_PASSWORD}
        keystore-type: PKCS12
