management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always

server:
   port: # Settes av miljøvariabel.
spring:
   output:
    ansi:
      enabled: always
   application:
      name: k9-dittnav-varsel
      admin:
         enabled: true
   mvc:
      log-request-details: true
