spring:
  mvc:
    log-request-details: false

kafka:
  onprem:
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${sts.username}" password="${sts.password}";
      ssl:
        trust-store-location: file:${javax.net.ssl.trustStore}
        trust-store-password: ${javax.net.ssl.trustStorePassword}
        trust-store-type: JKS
  aiven:
    properties:
      security:
        protocol: SSL
      ssl:
        truststore-location: file:${KAFKA_TRUSTSTORE_PATH}
        truststore-password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore-type: JKS
        keystore-location: file:${KAFKA_KEYSTORE_PATH}
        keystore-password: ${KAFKA_CREDSTORE_PASSWORD}
        keystore-type: PKCS12
