no.nav:
  sts:
    username: ${STS_USERNAME}
    password: ${STS_PASSWORD}

management:
   endpoints:
      web:
         exposure:
            include: health, prometheus
   endpoint:
      health:
         show-details: always
spring:
  kafka:
    bootstrap-servers:
    properties:
      schema:
        registry:
          url:
      security:
        protocol:
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${sts.username} password=${sts.password};
    producer:
      client-id: k9-dittnav-varsel
      retries: 3
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      ssl:
        trust-store-location: file:${javax.net.ssl.trustStore}
        trust-store-password: ${javax.net.ssl.trustStorePassword}
    consumer:
      enable-auto-commit: false
      group-id: group_id
      auto-offset-reset: earliest
      retry-interval: 60_000 # Egendefinert property
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      ssl:
        trust-store-location: file:${javax.net.ssl.trustStore}
        trust-store-password: ${javax.net.ssl.trustStorePassword}
  mvc:
    log-request-details: true
