kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: k9-brukerdialog-kafka-manager
  namespace: dusseldorf
  labels:
    team: dusseldorf
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/kafka-manager:2023.08.02-07.02-45dfb71
  port: 8080
  webproxy: true
  ingresses:
    - https://k9-brukerdialog-kafka-manager.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: b8f45495-7387-4627-8c00-be5ecca1d85f # dusseldorf
  kafka:
    pool: nav-prod
  env:
    - name: APP_CONFIG_JSON
      value: >
        {
          "topics": [
            {
              "name": "dusseldorf.privat-k9-dittnav-varsel-microfrontend",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }
