apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  port: 8080
  kafka:
    pool: {{kafkaPool}}
  accessPolicy:
    outbound:
      external:
      {{#each outboundRules as |host|}}
        - host: {{host}}
        {{/each}}
      rules: []
  liveness:
    path: /actuator/health
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 60
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 3072Mi
    requests:
      cpu: 60m
      memory: 750Mi
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: {{observabilityEnabled}}
      runtime: java
  env:
  {{#each env}}
   - name: {{@key}}
     value: "{{this}}"
  {{/each}}
