apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-k9-dittnav-varsel-beskjed
  namespace: dusseldorf
  labels:
    team: dusseldorf
spec:
  pool: {{kafka-pool}}
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 730  # -1 means unlimited
  acl:
    - team: dusseldorf
      application: k9-dittnav-varsel
      access: readwrite

    - team: dusseldorf
      application: omsorgsdager-aleneomsorg-prosessering
      access: write

    - team: dusseldorf
      application: omsorgspenger-midlertidig-alene-prosessering
      access: write

    - team: dusseldorf
      application: omsorgsdager-melding-prosessering
      access: write

    - team: dusseldorf
      application: k9-ettersending-prosessering
      access: write

    - team: dusseldorf
      application: omsorgspengesoknad-prosessering
      access: write

    - team: dusseldorf
      application: omsorgspengerutbetalingsoknad-prosessering
      access: write

    - team: dusseldorf
      application: sif-innsyn-api
      access: write

    - team: dusseldorf
      application: sif-karapace
      access: readwrite

    - team: dusseldorf
      application: pleiepenger-livets-sluttfase-prosessering
      access: write

    - team: dusseldorf
      application: omsorgspengerutbetalingsoknad-arbeidstaker-prosessering
      access: write
