name: Dependency Submission
on:
  push:
    branches:
      - master
    paths:
      - "**/build.gradle.kts"
      - ".github/workflows/gradle-dependency-submission.yml"
  workflow_dispatch:
  
jobs:
  scan:
    uses: navikt/sif-gha-workflows/.github/workflows/gradle-dependency-submission.yml@main
    secrets: inherit
    with:
      multi-module: false
