name: Monitor dependencies with Dependabot
on:
  push:
    branches:
      - master
    paths:
      - "**.gradle.kts"
      - ".github/workflows/dependency-submission.yml"
  workflow_dispatch:
jobs:
  dependabot:
    name: Monitor dependencies with Dependabot
    runs-on: ubuntu-20.04
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corrretto'
          java-version: '17'
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # ratchet:actions/checkout@v3
      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@aa82af7186ba17eb630a7d47c840ba8a3185ac91
        with:
          fail-on-error: true
          gradle-dependency-path: "build.gradle.kts"
