name: Create or update Kafka topics

on:
  push:
    paths:
      - 'nais/topics.yml'

jobs:
  deploy-kafka-topics-dev:
    name: Deploy to Aiven Dev
    if: startsWith(github.ref, 'refs/heads/dev-') || startsWith(github.ref, 'refs/heads/master') # Deploy if branch is either master or dev-*
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          VAR: kafka-pool=nav-dev
          RESOURCE: nais/topics.yml

  deploy-kafka-topics-prod:
    name: Deploy to Aiven Prod
    if: startsWith(github.ref, 'refs/heads/master')  # If the branch is master
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          VAR: kafka-pool=nav-prod
          RESOURCE: nais/topics.yml
