name: Deploy kafka manager
on:
  push:
    paths:
      - 'nais/kafka-manager.yaml'
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy-kafka-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        if: github.ref == 'refs/heads/master'
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/kafka-manager.yaml
